name: Triage

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: elnachto/laya-triage@main
